name: condaenv
channels:
  - conda-forge
dependencies:
  - graph-tool=2.45
  - jax=0.3.20
  - keras=2.10.0
  - loguru=0.6.0
  - mkl=2022.1.0
  - numba=0.56.2
  - numpy=1.23.3
  - pandas=1.4.4
  - pip=22.2.2
  - pytest=7.1.3
  - python=3.9.13
  - pytorch-cpu=1.12.1
  - pytorch-lightning=1.7.6
  - scikit-learn=1.1.2
  - scipy=1.9.1
  - tensorflow-cpu=2.10.0
  - tqdm=4.64.1
  - pip:
    - dm-haiku==0.0.8
    - flwr[simulation]==1.1.0
    - opacus==1.3.0
    - optax==0.1.3
    - tensorflow_privacy==0.7.3
    - tensorflow-probability==0.15.0
